CREATE TABLE comuna (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(255),
  id_region INT,
  FOREIGN KEY (id_region) REFERENCES region(id)
);

--los insert deben hacerse de 100 registros a la vez
--Parte1

INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PEÑAFLOR',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PADRE HURTADO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ISLA DE MAIPO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('EL MONTE',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TALAGANTE',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN PEDRO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MARIA PINTO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CURACAVI',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ALHUE',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MELIPILLA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PAINE',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CALERA DE TANGO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('BUIN',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN BERNARDO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TIL TIL',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAMPA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COLINA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN JOSE DE MAIPO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PIRQUE',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUENTE ALTO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VITACURA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN RAMON',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN MIGUEL',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN JOAQUIN',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RENCA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RECOLETA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUINTA NORMAL',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUILICURA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUDAHUEL',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PROVIDENCIA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PEÑALOLEN',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PEDRO AGUIRRE CERDA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ÑUÑOA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MAIPU',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MACUL',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LO PRADO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LO ESPEJO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LO BARNECHEA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAS CONDES',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA REINA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA PINTANA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA GRANJA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA FLORIDA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA CISTERNA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('INDEPENDENCIA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HUECHURABA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ESTACION CENTRAL',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('EL BOSQUE',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CONCHALI',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CERRO NAVIA',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CERRILLOS',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SANTIAGO',13);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TORRES DEL PAINE',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NATALES',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TIMAUKEL',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PRIMAVERA',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PORVENIR',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ANTÁRTICA',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CABO DE HORNOS',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN GREGORIO',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RIO VERDE',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAGUNA BLANCA',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUNTA ARENAS',12);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RIO IBAÑEZ',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHILE CHICO',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TORTEL',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('OHIGGINS',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COYHAIQUE / COIHAIQUE',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COCHRANE',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('GUAITECAS',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CISNES',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('AYSEN / AISEN',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAGO VERDE',11);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PALENA',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HUALAIHUE',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('FUTALEUFU',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHAITEN',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN PABLO',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN JUAN DE LA COSTA',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RIO NEGRO',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUYEHUE',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PURRANQUE',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUERTO OCTAY',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('OSORNO',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUINCHAO',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUEMCHI',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUELLON',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUEILEN',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUQUELDON',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('DALCAHUE',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CURACO DE VELEZ',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHONCHI',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ANCUD',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CASTRO',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUERTO VARAS',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MAULLIN',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LLANQUIHUE',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOS MUERMOS',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('FRUTILLAR',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('FRESIA',10);

--Parte 2

INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COCHAMO',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CALBUCO',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUERTO MONTT',10);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RIO BUENO',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAGO RANCO',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('FUTRONO',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA UNION',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PANGUIPULLI',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PAILLACO',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MARIQUINA',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MAFIL',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOS LAGOS',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LANCO',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CORRAL',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VALDIVIA',14);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VICTORIA',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TRAIGUEN',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RENAICO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUREN',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LUMACO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOS SAUCES',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LONQUIMAY',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CURACAUTIN',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COLLIPULLI',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ERCILLA',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ANGOL',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHOLCHOL',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VILLARRICA',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VILCUN',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TOLTEN',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TEODORO SCHMIDT',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAAVEDRA',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUCON',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PITRUFQUEN',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PERQUENCO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PADRE LAS CASAS',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NUEVA IMPERIAL',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MELIPEUCO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LONCOCHE',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAUTARO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('GORBEA',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('GALVARINO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('FREIRE',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CURARREHUE',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CUNCO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CARAHUE',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TEMUCO',9);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ALTO BIO BIO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('YUMBEL',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TUCAPEL',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SANTA BARBARA',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN ROSENDO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUILLECO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUILACO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NEGRETE',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NACIMIENTO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MULCHEN',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAJA',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CABRERO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ANTUCO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOS ANGELES',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TIRUA',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOS ALAMOS',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CURANILAHUE',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CONTULMO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CAÑETE',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ARAUCO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LEBU',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HUALPEN',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TOME',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TALCAHUANO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SANTA JUANA',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN PEDRO DE LA PAZ',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PENCO',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOTA',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HUALQUI',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('FLORIDA',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHIGUAYANTE',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CORONEL',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CONCEPCION',8);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('YUNGAY',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TREGUACO / TREHUACO',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN NICOLAS',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN IGNACIO',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN FABIAN',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN CARLOS',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RANQUIL',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUIRIHUE',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUILLON',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PORTEZUELO',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PINTO',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PEMUCO',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ÑIQUEN',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NINHUE',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('EL CARMEN',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHILLAN VIEJO',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COIHUECO',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COELEMU',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COBQUECURA',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('BULNES',16);

--Parte 3

INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHILLAN',16);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('YERBAS BUENAS',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VILLA ALEGRE',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN JAVIER',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RETIRO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PARRAL',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LONGAVI',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COLBUN',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LINARES',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VICHUQUEN',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TENO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAGRADA FAMILIA',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ROMERAL',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RAUCO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MOLINA',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LICANTEN',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HUALAÑE',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CURICO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PELLUHUE',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHANCO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CAUQUENES',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN RAFAEL',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN CLEMENTE',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RIO CLARO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PENCAHUE',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PELARCO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MAULE',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('EMPEDRADO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CUREPTO',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CONSTITUCION',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TALCA',7);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SANTA CRUZ',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUMANQUE',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PLACILLA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PERALILLO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PALMILLA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NANCAGUA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOLOL',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHIMBARONGO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN FERNANDO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHEPICA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PAREDONES',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NAVIDAD',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MARCHIHUE',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LITUECHE',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA ESTRELLA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PICHILEMU',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN VICENTE',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RENGO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('REQUINOA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUINTA DE TILCOCO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PICHIDEGUA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PEUMO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('OLIVAR',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MOSTAZAL',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MALLOA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MACHALI',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LAS CABRAS',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('GRANEROS',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('DOÑIHUE',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COLTAUCO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COINCO',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CODEGUA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RANCAGUA',6);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('OLMUE',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUILPUE',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VILLA ALEMANA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LIMACHE',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SANTA MARIA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUTAENDO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PANQUEHUE',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CATEMU',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LLAILLAY / LLAYLLAY',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN FELIPE',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SANTO DOMINGO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('EL TABO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('EL QUISCO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CARTAGENA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ALGARROBO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN ANTONIO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('NOGALES',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA CRUZ',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HIJUELAS',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA CALERA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUILLOTA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ZAPALLAR',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PETORCA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PAPUDO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CABILDO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA LIGUA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN ESTEBAN',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RINCONADA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CALLE LARGA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOS ANDES',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ISLA DE PASCUA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VIÑA DEL MAR',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('QUINTERO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUCHUNCAVI',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ISLA JUAN FERNANDEZ',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CONCON',5);

--Parte 4

INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CASABLANCA',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VALPARAISO',5);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('RIO HURTADO',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUNITAQUI',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MONTE PATRIA',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COMBARBALA',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('OVALLE',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LOS VILOS',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SALAMANCA',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CANELA',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ILLAPEL',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VICUÑA',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PAIHUANO',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA HIGUERA',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ANDACOLLO',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COQUIMBO',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('LA SERENA',4);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HUASCO',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('FREIRINA',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ALTO DEL CARMEN',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CHAÑARAL',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TIERRA AMARILLA',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('VALLENAR',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('DIEGO DE ALMAGRO',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CALDERA',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COPIAPO',3);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SAN PEDRO DE ATACAMA',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('SIERRA GORDA',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MEJILLONES',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('MARIA ELENA',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TOCOPILLA',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('OLLAGÜE',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CALAMA',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('TALTAL',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ANTOFAGASTA',2);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PICA',1);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('HUARA',1);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('COLCHANE',1);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CAMIÑA',1);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('POZO ALMONTE',1);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('IQUIQUE',1);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ALTO HOSPICIO',1);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('ARICA',15);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('GENERAL LAGOS',15);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('PUTRE',15);
INSERT INTO `comuna`(`nombre`, `id_region`) VALUES ('CAMARONES',15);



